(function(root){'use strict';root.initObjectEditor=function({getProject,commit,message,openData}){
  const $=id=>document.getElementById(id),M=root.LabelStudio;let selected='text:0',drag=null,lastLabel=null;
  function current(){const s=getProject();return{s,l:s.labels[s.selected],g:s.geometry};}
  function textStyle(){return{text:'새 텍스트',font:'sans',size:12,color:'#355e48',bold:false,align:'center'};}
  function objects(){const{s,l,g}=current(),base=root.LabelPDF.safeRect({x:0,y:0,width:g.width,height:g.height},g.shape);return[
    {key:'text:0',type:'text',index:0,name:'기본 텍스트',data:l,box:l.textBox||base,z:l.textZ??100},
    ...(l.textBoxes||[]).map((t,i)=>({key:'text:'+(i+1),type:'text',index:i+1,name:'텍스트 '+(i+2),data:t,box:t.textBox,z:t.z??101+i})),
    ...(l.images||[]).map((t,i)=>({key:'image:'+i,type:'image',index:i,name:'이미지 '+(i+1),data:t,box:t,z:t.z??i}))];}
  function active(){return objects().find(o=>o.key===selected);}
  function change(fn){commit(s=>{fn(s,s.labels[s.selected]);M.prune(s);});refresh();}
  function place(el,b,g){Object.assign(el.style,{left:b.x/g.width*100+'%',top:b.y/g.height*100+'%',width:b.width/g.width*100+'%',height:b.height/g.height*100+'%'});}
  function updateBox(o,b){if(o.type==='image')Object.assign(o.data,b);else o.data.textBox={x:b.x,y:b.y,width:b.width,height:b.height};}
  function refresh(){const{s,l,g}=current();if(l!==lastLabel){lastLabel=l;selected='text:0';}const list=objects();if(!list.some(o=>o.key===selected))selected='text:0';
    $('studio-label').textContent=`${s.selected+1}번 라벨 · ${g.width} × ${g.height} mm`;
    const stage=$('object-stage');stage.style.aspectRatio=`${g.width}/${g.height}`;stage.style.borderRadius=g.shape==='ellipse'?'50%':'0';stage.replaceChildren();
    const select=$('image-selection');select.replaceChildren();for(const o of list){const option=document.createElement('option');option.value=o.key;option.textContent=o.name;select.append(option);}
    for(const o of list.sort((a,b)=>a.z-b.z)){
      const el=document.createElement('div');el.className='studio-object '+(o.type==='image'?'studio-image':'studio-text')+(o.key===selected?' active':'');el.dataset.object=o.key;el.style.zIndex=String(o.z);place(el,o.box,g);
      if(o.type==='image'){const img=document.createElement('img');img.src=s.assets[o.data.assetId].data;img.alt=o.name;img.draggable=false;el.append(img);}else{el.textContent=o.data.text;Object.assign(el.style,{fontSize:`${o.data.size*25.4/72/g.width*100}cqw`,fontFamily:`"Label ${o.data.font==='serif'?'Serif':o.data.font==='mono'?'Mono':'Sans'}"`,fontWeight:o.data.bold?'700':'400',color:o.data.color,textAlign:o.data.align});}
      el.addEventListener('pointerdown',e=>startDrag(e,o,false,el));stage.append(el);
      if(o.key===selected){const handle=document.createElement('button');handle.className='object-resize';handle.setAttribute('aria-label',o.name+' 크기 조절');handle.style.left=(o.box.x+o.box.width)/g.width*100+'%';handle.style.top=(o.box.y+o.box.height)/g.height*100+'%';handle.style.zIndex='20001';handle.addEventListener('pointerdown',e=>startDrag(e,o,true,el));stage.append(handle);}
    }syncFields();
  }
  function syncFields(){const o=active();$('image-selection').value=selected;for(const k of ['x','y','width','height'])$('image-'+k).value=o?Number(o.box[k].toFixed(3)):'';const isText=o?.type==='text';$('object-text-settings').hidden=!isText;if(isText){$('object-text').value=o.data.text;$('object-font').value=o.data.font;$('object-size').value=o.data.size;$('object-color').value=o.data.color;$('object-bold').checked=o.data.bold;$('object-align').value=o.data.align;}}
  function startDrag(e,o,resize,el){e.preventDefault();e.stopPropagation();selected=o.key;const stage=$('object-stage'),r=stage.getBoundingClientRect(),{s,g}=current();stage.querySelectorAll('.studio-object').forEach(n=>n.classList.toggle('active',n.dataset.object===selected));syncFields();drag={id:e.pointerId,key:o.key,startX:e.clientX,startY:e.clientY,box:{...o.box},sx:g.width/r.width,sy:g.height/r.height,project:s,label:s.selected,resize,el};stage.setPointerCapture(e.pointerId);}
  $('object-stage').addEventListener('pointermove',e=>{if(!drag||drag.id!==e.pointerId)return;const{s,g}=current();if(s!==drag.project||s.selected!==drag.label)return;const dx=(e.clientX-drag.startX)*drag.sx,dy=(e.clientY-drag.startY)*drag.sy;const b=drag.resize?{...drag.box,width:Math.max(.5,Math.min(g.width-drag.box.x,drag.box.width+dx)),height:Math.max(.5,Math.min(g.height-drag.box.y,drag.box.height+dy))}:M.fit({...drag.box,x:drag.box.x+dx,y:drag.box.y+dy},g);place(drag.el,b,g);const h=$('object-stage').querySelector('.object-resize');if(h){h.style.left=(b.x+b.width)/g.width*100+'%';h.style.top=(b.y+b.height)/g.height*100+'%';}drag.pending=b;});
  $('object-stage').addEventListener('pointerup',e=>{if(!drag||drag.id!==e.pointerId)return;const d=drag;drag=null;if(d.pending&&getProject()===d.project&&getProject().selected===d.label)change(()=>updateBox(active(),d.pending));else refresh();});
  $('object-stage').addEventListener('pointercancel',()=>{drag=null;refresh();});
  $('image-selection').addEventListener('change',()=>{selected=$('image-selection').value;refresh();});
  for(const k of ['x','y','width','height'])$('image-'+k).addEventListener('change',()=>{const o=active(),b={...o.box,[k]:Number($('image-'+k).value)};if(!M.box(b,current().g)){message('위치·크기는 라벨 영역 안으로 입력하세요.');syncFields();return;}change(()=>updateBox(o,b));});
  $('add-text').addEventListener('click',()=>{const{l,g}=current();if((l.textBoxes||[]).length>=19){message('텍스트 박스는 라벨당 20개까지 지원합니다.');return;}const base=root.LabelPDF.safeRect({x:0,y:0,width:g.width,height:g.height},g.shape);change((s,l)=>{l.textBoxes||=[];l.textBoxes.push({...textStyle(),textBox:{...base},z:Math.max(...objects().map(o=>o.z))+1});selected='text:'+l.textBoxes.length;});});
  $('remove-image').addEventListener('click',()=>{const o=active();change((s,l)=>{if(o.type==='image')l.images.splice(o.index,1);else if(o.index)l.textBoxes.splice(o.index-1,1);else{l.text='';delete l.textBox;}selected='text:0';});});
  for(const [id,front] of [['image-forward',true],['object-backward',false]])$(id).addEventListener('click',()=>{const o=active(),value=(front?Math.max(...objects().map(i=>i.z))+1:Math.min(...objects().map(i=>i.z))-1);change(()=>{if(o.key==='text:0')o.data.textZ=value;else o.data.z=value;});});
  for(const [id,key,event] of [['object-text','text','input'],['object-font','font','change'],['object-size','size','change'],['object-color','color','input'],['object-bold','bold','change'],['object-align','align','change']])$(id).addEventListener(event,()=>{const o=active();if(o.type!=='text')return;const value=key==='size'?Math.max(6,Math.min(48,Number($(id).value)||12)):key==='bold'?$(id).checked:$(id).value;
    // Do not rebuild the input while typing: keep caret and focus intact.
    commit(()=>o.data[key]=value);});
  $('object-data').addEventListener('click',()=>openData(active()?.type==='text'?active().index:0));
  $('open-studio').addEventListener('click',()=>{selected='text:0';refresh();$('studio-dialog').showModal();});
async function addFile(file){const snapshot=getProject(),label=snapshot.selected;try{if(!file||!['image/png','image/jpeg','image/webp'].includes(file.type))throw Error('PNG, JPG, WebP 이미지를 선택해 주세요.');if(file.size>8*1024*1024)throw Error('이미지는 파일당 8MB까지 지원합니다.');const url=await new Promise((res,rej)=>{const r=new FileReader();r.onload=()=>res(r.result);r.onerror=()=>rej(Error('이미지를 읽지 못했습니다.'));r.readAsDataURL(file);});const image=await new Promise((res,rej)=>{const im=new Image();im.onload=()=>res(im);im.onerror=()=>rej(Error('이미지 형식을 확인해 주세요.'));im.src=url;});if(image.naturalWidth*image.naturalHeight>25000000)throw Error('이미지는 2,500만 화소까지 지원합니다.');let imageData=url;if(file.type==='image/webp'){const canvas=document.createElement('canvas');canvas.width=image.naturalWidth;canvas.height=image.naturalHeight;canvas.getContext('2d').drawImage(image,0,0);imageData=canvas.toDataURL('image/png');}if(imageData.length>M.MAX_ASSET)throw Error('변환된 이미지가 너무 큽니다. 크기를 줄여 주세요.');if(getProject()!==snapshot||snapshot.selected!==label)throw Error('선택한 라벨이 바뀌었습니다. 이미지를 다시 추가해 주세요.');if((snapshot.labels[label].images||[]).length>=20)throw Error('한 라벨에는 이미지 20개까지 추가할 수 있습니다.');const used=Object.values(snapshot.assets||{}).reduce((n,a)=>n+a.data.length,0);if(used+imageData.length>M.MAX_TOTAL)throw Error('프로젝트 이미지 용량을 줄여 주세요.');const g=snapshot.geometry,factor=g.shape==='ellipse'?Math.SQRT1_2:1,scale=Math.min(g.width*factor*.7/image.naturalWidth,g.height*factor*.7/image.naturalHeight),width=image.naturalWidth*scale,height=image.naturalHeight*scale;const id='img_'+Date.now().toString(36)+'_'+Math.random().toString(36).slice(2,8);change((s,l)=>{s.assets||={};s.assets[id]={data:imageData};l.images||=[];l.images.push({assetId:id,x:(g.width-width)/2,y:(g.height-height)/2,width,height});selected='image:'+(l.images.length-1);});message('이미지를 추가했습니다. 드래그하거나 mm 수치로 위치·크기를 조절하세요.');}catch(e){message(e);}}
$('image-file').addEventListener('change',()=>{const file=$('image-file').files[0];$('image-file').value='';if(file)addFile(file);});$('add-image').addEventListener('click',()=>$('image-file').click());
$('studio-dialog').addEventListener('paste',e=>{const item=Array.from(e.clipboardData?.items||[]).find(i=>i.kind==='file'&&i.type.startsWith('image/'));if(item){e.preventDefault();addFile(item.getAsFile());}});
$('object-stage').addEventListener('dragover',e=>e.preventDefault());$('object-stage').addEventListener('drop',e=>{e.preventDefault();addFile(e.dataTransfer.files[0]);});

  function isTyping(){return ['object-text','object-size','object-color'].includes(document.activeElement?.id);}
  return{refresh(){if(!$('studio-dialog').open)return;const focus=isTyping()?document.activeElement:null,start=focus?.selectionStart,end=focus?.selectionEnd;refresh();if(focus){focus.focus();if(start!==null&&start!==undefined)focus.setSelectionRange(start,end);}},addImage:async()=>{}};
};})(globalThis);
