(function(root){'use strict';root.initStudioUI=function({getProject,commit,notify}){
const $=id=>document.getElementById(id),M=root.LabelStudio;let loaded=null,data=null,undo=null,addressLoader=null,matrix=[],bookPage=0;
function message(e){for(const id of ['studio-message','data-message','address-message'])$(id).textContent=e.message||e;notify(e.message||e);}
function change(fn){commit(s=>{fn(s,s.labels[s.selected]);M.prune(s);});}
function targets(index=0){const l=getProject().labels[getProject().selected];$('data-target').replaceChildren();for(let i=0;i<= (l.textBoxes||[]).length;i++){const o=document.createElement('option');o.value=i;o.textContent=i?'텍스트 '+(i+1):'기본 텍스트';$('data-target').append(o);}$('data-target').value=index;}
const editor=root.initObjectEditor({getProject,commit,message,openData:index=>{targets(index);$('data-dialog').showModal();if(data)previewData();}});
// Spreadsheet values are parsed locally; formulas are never evaluated.
$('data-file').addEventListener('change',async()=>{const file=$('data-file').files[0];loaded=null;data=null;matrix=[];$('show-addressbook').disabled=true;$('addressbook-table').replaceChildren();$('apply-data').disabled=true;try{if(!file)return;if(file.size>10*1024*1024)throw Error('자료 파일은 10MB까지 지원합니다.');loaded=root.XLSX.read(await file.arrayBuffer(),{type:'array',cellFormula:false,sheetRows:10002,raw:true,codepage:65001});$('data-sheet').replaceChildren();for(const name of loaded.SheetNames){const opt=document.createElement('option');opt.textContent=name;opt.value=name;$('data-sheet').append(opt);}loadSheet();}catch(e){message(e);}finally{$('data-file').value='';}});
function loadSheet(){try{const sheet=loaded.Sheets[$('data-sheet').value];const range=root.XLSX.utils.decode_range(sheet['!fullref']||sheet['!ref']||'A1');if(range.e.r>10000||range.e.c>99)throw Error('주소록은 10,001행(제목 포함)·100열까지 지원합니다.');matrix=root.XLSX.utils.sheet_to_json(sheet,{header:1,raw:false,defval:'',blankrows:true,range:{s:{r:0,c:0},e:range.e}});data=M.table(matrix.length===1?[matrix[0],[]]:matrix);$('show-addressbook').disabled=false;bookPage=0;$('addressbook-search').value='';$('data-ref-mode').value='headers';$('cell-advance').checked=false;$('data-columns').replaceChildren();for(const h of data.headers){const b=document.createElement('button');b.className='column-chip';b.textContent=h;b.addEventListener('click',()=>{$('data-ref-mode').value='headers';$('data-template').value+='{{'+h+'}}';previewData();});$('data-columns').append(b);}$('data-template').value=data.headers.map(h=>'{{'+h+'}}').join('\n');$('data-row-start').value=1;$('data-label-start').value=getProject().selected+1;previewData();}catch(e){data=null;$('apply-data').disabled=true;message(e);}}
function values(){if(!data)throw Error('먼저 엑셀 또는 CSV를 선택하세요.');return $('data-ref-mode').value==='cells'?M.cellMerge(matrix,$('data-template').value,$('cell-advance').checked):M.merge(data,$('data-template').value);}
function previewData(){try{const rows=values(),from=Number($('data-row-start').value),start=Number($('data-label-start').value),capacity=getProject().labels.length-start+1;if(!Number.isInteger(from)||from<1||from>rows.length||!Number.isInteger(start)||start<1||capacity<1)throw Error('자료 시작 행과 라벨 시작 칸을 확인하세요.');const count=Math.min(capacity,rows.length-from+1);$('data-preview').textContent=rows.slice(from-1,from-1+Math.min(3,count)).map((t,i)=>`${from+i}행 → ${start+i}번\n${t}`).join('\n\n');$('data-summary').textContent=`총 ${rows.length}행 · 이번에 ${count}칸 입력 · 남은 ${Math.max(0,rows.length-from+1-count)}행은 다음 용지에서 입력하세요. 해당 칸의 기존 문구를 바꿉니다.`;$('apply-data').disabled=false;}catch(e){$('data-summary').textContent=e.message;$('apply-data').disabled=true;}}
$('data-sheet').addEventListener('change',()=>{loadSheet();if($('addressbook-dialog').open)renderBook();});
$('data-ref-mode').addEventListener('change',()=>{$('data-row-start').value=1;previewData();});$('cell-advance').addEventListener('change',()=>{$('data-row-start').value=1;previewData();});
function renderBook(){const query=$('addressbook-search').value.trim().toLowerCase();const indexes=matrix.map((row,i)=>i).filter(i=>!query||matrix[i].some(v=>String(v).toLowerCase().includes(query)));const pages=Math.max(1,Math.ceil(indexes.length/50));bookPage=Math.min(bookPage,pages-1);$('addressbook-page').textContent=`${bookPage+1} / ${pages} 페이지 · ${indexes.length}행 · ${$('data-sheet').value}`;$('addressbook-prev').disabled=bookPage===0;$('addressbook-next').disabled=bookPage===pages-1;const table=$('addressbook-table');table.replaceChildren();const head=document.createElement('thead'),hr=document.createElement('tr');const corner=document.createElement('th');corner.textContent='행';hr.append(corner);const width=Math.max(0,...matrix.map(r=>r.length));for(let c=0;c<width;c++){const th=document.createElement('th');th.scope='col';th.textContent=M.columnName(c);hr.append(th);}head.append(hr);table.append(head);const body=document.createElement('tbody');for(const rowIndex of indexes.slice(bookPage*50,bookPage*50+50)){const tr=document.createElement('tr'),th=document.createElement('th');th.scope='row';th.textContent=rowIndex+1;tr.append(th);for(let c=0;c<width;c++){const td=document.createElement('td'),b=document.createElement('button');const ref=M.columnName(c)+(rowIndex+1);b.textContent=String(matrix[rowIndex][c]??'')||'　';b.title=ref;b.dataset.cell=ref;b.setAttribute('aria-label',ref+': '+String(matrix[rowIndex][c]??'빈 셀'));b.addEventListener('click',()=>{const input=$('data-template');input.setRangeText('{{'+ref+'}}',input.selectionStart,input.selectionEnd,'end');$('data-ref-mode').value='cells';$('data-row-start').value=1;$('addressbook-selection').textContent=ref+' 참조를 문구에 넣었습니다.';previewData();});td.append(b);tr.append(td);}body.append(tr);}table.append(body);}
document.querySelector('.close-addressbook').addEventListener('click',()=>$('addressbook-dialog').close());
$('show-addressbook').addEventListener('click',()=>{if(!data)return;renderBook();$('addressbook-dialog').showModal();});$('addressbook-search').addEventListener('input',()=>{bookPage=0;renderBook();});$('addressbook-prev').addEventListener('click',()=>{bookPage--;renderBook();});$('addressbook-next').addEventListener('click',()=>{bookPage++;renderBook();});for(const id of ['data-template','data-row-start','data-label-start'])$(id).addEventListener('input',previewData);
$('apply-data').addEventListener('click',()=>{try{const rows=values(),from=Number($('data-row-start').value)-1,start=Number($('data-label-start').value)-1;previewData();if($('apply-data').disabled)return;undo={project:getProject(),product:getProject().product,texts:getProject().labels.map(l=>({text:l.text,textBoxes:JSON.parse(JSON.stringify(l.textBoxes||[]))}))};const n=Math.min(rows.length-from,getProject().labels.length-start);change(s=>{const target=Number($('data-target').value);const source=s.labels[s.selected];for(let i=0;i<n;i++){const label=s.labels[start+i];if(!target)label.text=rows[from+i];else{label.textBoxes||=[];while(label.textBoxes.length<target)label.textBoxes.push({...JSON.parse(JSON.stringify(source.textBoxes[target-1])),text:''});label.textBoxes[target-1].text=rows[from+i];}}});$('undo-data').disabled=false;message(`${n}칸에 문구를 입력했습니다. PDF에서 넘침을 확인하세요.`);}catch(e){message(e);}});
$('undo-data').addEventListener('click',()=>{if(!undo||getProject()!==undo.project||getProject().product!==undo.product||getProject().labels.length!==undo.texts.length){message('프로젝트가 바뀌어 되돌릴 수 없습니다.');return;}change(s=>s.labels.forEach((l,i)=>{l.text=undo.texts[i].text;l.textBoxes=undo.texts[i].textBoxes;}));undo=null;$('undo-data').disabled=true;});
$('open-data').addEventListener('click',()=>{targets();$('data-dialog').showModal();if(data)previewData();});
$('open-address').addEventListener('click',()=>$('address-dialog').showModal());
$('search-address').addEventListener('click',async()=>{try{if(!addressLoader)addressLoader=new Promise((res,rej)=>{const script=document.createElement('script');script.src='https://t1.kakaocdn.net/mapjsapi/bundle/postcode/prod/postcode.v2.js';script.onload=res;script.onerror=()=>{addressLoader=null;script.remove();rej(Error('주소 검색 서비스를 불러오지 못했습니다. 직접 입력하거나 연결을 확인하세요.'));};document.head.append(script);});await addressLoader;const service=root.kakao?.Postcode||root.daum?.Postcode;if(!service)throw Error('주소 검색 서비스를 사용할 수 없습니다.');$('address-search-frame').hidden=false;new service({width:'100%',height:'100%',oncomplete:d=>{$('address-postcode').value=d.zonecode;$('address-main').value=d.userSelectedType==='R'?d.roadAddress:d.jibunAddress;$('address-search-frame').hidden=true;$('address-detail').focus();}}).embed($('address-search-frame'));}catch(e){message(e);}});
$('apply-address').addEventListener('click',()=>{const text=[$('address-postcode').value,$('address-main').value,$('address-detail').value,$('address-recipient').value].map(s=>s.trim()).filter(Boolean).join('\n');if(!$('address-main').value.trim()||text.length>1000){message('주소를 입력해 주세요.');return;}change((s,l)=>l.text=text);$('address-dialog').close();notify('선택한 라벨에 주소를 입력했습니다.');});
return{refresh:()=>editor.refresh()};
};})(globalThis);
