(function(root){'use strict';root.initStudioUI=function({getProject,commit,notify}){
const $=id=>document.getElementById(id),M=root.LabelStudio;let selected=-1,loaded=null,data=null,undo=null,addressLoader=null,drag=null;
function current(){const s=getProject();return{s,l:s.labels[s.selected],g:s.geometry};}
function message(e){for(const id of ['studio-message','data-message','address-message'])$(id).textContent=e.message||e;notify(e.message||e);}
function change(fn){commit(s=>{fn(s,s.labels[s.selected]);M.prune(s);});refresh();}
function refresh(){const{s,l,g}=current();$('studio-label').textContent=`${s.selected+1}번 라벨 · ${g.width} × ${g.height} mm`;
const stage=$('object-stage');stage.style.aspectRatio=`${g.width}/${g.height}`;stage.style.borderRadius=g.shape==='ellipse'?'50%':'0';stage.replaceChildren();
const text=document.createElement('div');text.className='studio-text';text.textContent=l.text;const t=l.textBox||root.LabelPDF.safeRect({x:0,y:0,width:g.width,height:g.height},g.shape);place(text,t,g);text.style.fontSize=`${l.size*25.4/72/g.width*100}cqw`;text.style.textAlign=l.align;text.style.fontWeight=l.bold?'700':'400';text.style.color=l.color;text.style.fontFamily=`"Label ${l.font==='serif'?'Serif':l.font==='mono'?'Mono':'Sans'}"`;stage.append(text);
const select=$('image-selection');select.replaceChildren();(l.images||[]).forEach((item,i)=>{const opt=document.createElement('option');opt.value=i;opt.textContent=`이미지 ${i+1}`;select.append(opt);const image=document.createElement('img');image.src=s.assets[item.assetId].data;image.alt=`이미지 ${i+1}`;image.draggable=false;image.className='studio-image'+(selected===i?' active':'');place(image,item,g);image.addEventListener('pointerdown',e=>{e.preventDefault();selected=i;const r=stage.getBoundingClientRect();drag={id:e.pointerId,index:i,startX:e.clientX,startY:e.clientY,box:{...item},sx:g.width/r.width,sy:g.height/r.height,project:s,label:s.selected};stage.setPointerCapture(e.pointerId);syncFields();});stage.append(image);});if(selected<0&&(l.images||[]).length)selected=0;if(selected>=(l.images||[]).length)selected=(l.images||[]).length-1;select.value=selected;syncFields();}
function place(el,b,g){Object.assign(el.style,{left:b.x/g.width*100+'%',top:b.y/g.height*100+'%',width:b.width/g.width*100+'%',height:b.height/g.height*100+'%'});}
function syncFields(){const{l}=current(),item=l.images?.[selected];$('image-selection').value=selected;for(const k of ['x','y','width','height']){$('image-'+k).disabled=!item;$('image-'+k).value=item?Number(item[k].toFixed(3)):'';}$('remove-image').disabled=!item;$('image-forward').disabled=!item;}
$('object-stage').addEventListener('pointermove',e=>{if(!drag||drag.id!==e.pointerId)return;const{s,l,g}=current();if(s!==drag.project||s.selected!==drag.label)return;const b=M.fit({...drag.box,x:drag.box.x+(e.clientX-drag.startX)*drag.sx,y:drag.box.y+(e.clientY-drag.startY)*drag.sy},g);const el=$('object-stage').querySelectorAll('.studio-image')[drag.index];if(el)place(el,b,g);drag.pending=b;});
function endDrag(e){if(!drag||drag.id!==e.pointerId)return;const d=drag;drag=null;if(d.pending&&getProject()===d.project&&getProject().selected===d.label)change((s,l)=>l.images[d.index]=d.pending);}
$('object-stage').addEventListener('pointerup',endDrag);$('object-stage').addEventListener('pointercancel',()=>{drag=null;refresh();});
$('image-selection').addEventListener('change',()=>{selected=Number($('image-selection').value);refresh();});
for(const k of ['x','y','width','height'])$('image-'+k).addEventListener('change',()=>{const{l,g}=current();if(!l.images?.[selected])return;const candidate={...l.images[selected],[k]:Number($('image-'+k).value)};if(!M.box(candidate,g)){message('이미지가 라벨 영역 안에 들어오도록 위치·크기를 입력하세요.');syncFields();return;}change((s,l)=>l.images[selected]=candidate);});
$('remove-image').addEventListener('click',()=>change((s,l)=>{l.images.splice(selected,1);selected=-1;}));
$('image-forward').addEventListener('click',()=>change((s,l)=>{l.images.push(l.images.splice(selected,1)[0]);selected=l.images.length-1;}));
async function addFile(file){const snapshot=getProject(),label=snapshot.selected;try{if(!file||!['image/png','image/jpeg','image/webp'].includes(file.type))throw Error('PNG, JPG, WebP 이미지를 선택해 주세요.');if(file.size>8*1024*1024)throw Error('이미지는 파일당 8MB까지 지원합니다.');const url=await new Promise((res,rej)=>{const r=new FileReader();r.onload=()=>res(r.result);r.onerror=()=>rej(Error('이미지를 읽지 못했습니다.'));r.readAsDataURL(file);});const image=await new Promise((res,rej)=>{const im=new Image();im.onload=()=>res(im);im.onerror=()=>rej(Error('이미지 형식을 확인해 주세요.'));im.src=url;});if(image.naturalWidth*image.naturalHeight>25000000)throw Error('이미지는 2,500만 화소까지 지원합니다.');let imageData=url;if(file.type==='image/webp'){const canvas=document.createElement('canvas');canvas.width=image.naturalWidth;canvas.height=image.naturalHeight;canvas.getContext('2d').drawImage(image,0,0);imageData=canvas.toDataURL('image/png');}if(imageData.length>M.MAX_ASSET)throw Error('변환된 이미지가 너무 큽니다. 크기를 줄여 주세요.');if(getProject()!==snapshot||snapshot.selected!==label)throw Error('선택한 라벨이 바뀌었습니다. 이미지를 다시 추가해 주세요.');if((snapshot.labels[label].images||[]).length>=20)throw Error('한 라벨에는 이미지 20개까지 추가할 수 있습니다.');const used=Object.values(snapshot.assets||{}).reduce((n,a)=>n+a.data.length,0);if(used+imageData.length>M.MAX_TOTAL)throw Error('프로젝트 이미지 용량을 줄여 주세요.');const g=snapshot.geometry,factor=g.shape==='ellipse'?Math.SQRT1_2:1,scale=Math.min(g.width*factor*.7/image.naturalWidth,g.height*factor*.7/image.naturalHeight),width=image.naturalWidth*scale,height=image.naturalHeight*scale;const id='img_'+Date.now().toString(36)+'_'+Math.random().toString(36).slice(2,8);change((s,l)=>{s.assets||={};s.assets[id]={data:imageData};l.images||=[];l.images.push({assetId:id,x:(g.width-width)/2,y:(g.height-height)/2,width,height});selected=l.images.length-1;});message('이미지를 추가했습니다. 드래그하거나 mm 수치로 위치·크기를 조절하세요.');}catch(e){message(e);}}
$('image-file').addEventListener('change',()=>{const file=$('image-file').files[0];$('image-file').value='';if(file)addFile(file);});$('add-image').addEventListener('click',()=>$('image-file').click());
$('studio-dialog').addEventListener('paste',e=>{const item=Array.from(e.clipboardData?.items||[]).find(i=>i.kind==='file'&&i.type.startsWith('image/'));if(item){e.preventDefault();addFile(item.getAsFile());}});
$('object-stage').addEventListener('dragover',e=>e.preventDefault());$('object-stage').addEventListener('drop',e=>{e.preventDefault();addFile(e.dataTransfer.files[0]);});
$('open-studio').addEventListener('click',()=>{selected=-1;refresh();$('studio-dialog').showModal();});
// Spreadsheet values are parsed locally; formulas are never evaluated.
$('data-file').addEventListener('change',async()=>{const file=$('data-file').files[0];loaded=null;data=null;$('apply-data').disabled=true;try{if(!file)return;if(file.size>10*1024*1024)throw Error('자료 파일은 10MB까지 지원합니다.');loaded=root.XLSX.read(await file.arrayBuffer(),{type:'array',cellFormula:false,sheetRows:10002,raw:true,codepage:65001});$('data-sheet').replaceChildren();for(const name of loaded.SheetNames){const opt=document.createElement('option');opt.textContent=name;opt.value=name;$('data-sheet').append(opt);}loadSheet();}catch(e){message(e);}finally{$('data-file').value='';}});
function loadSheet(){try{data=M.table(root.XLSX.utils.sheet_to_json(loaded.Sheets[$('data-sheet').value],{header:1,raw:false,defval:''}));$('data-columns').replaceChildren();for(const h of data.headers){const b=document.createElement('button');b.className='column-chip';b.textContent=h;b.addEventListener('click',()=>{$('data-template').value+='{{'+h+'}}';previewData();});$('data-columns').append(b);}$('data-template').value=data.headers.map(h=>'{{'+h+'}}').join('\n');$('data-row-start').value=1;$('data-label-start').value=getProject().selected+1;previewData();}catch(e){data=null;$('apply-data').disabled=true;message(e);}}
function values(){if(!data)throw Error('먼저 엑셀 또는 CSV를 선택하세요.');return M.merge(data,$('data-template').value);}
function previewData(){try{const rows=values(),from=Number($('data-row-start').value),start=Number($('data-label-start').value),capacity=getProject().labels.length-start+1;if(!Number.isInteger(from)||from<1||from>rows.length||!Number.isInteger(start)||start<1||capacity<1)throw Error('자료 시작 행과 라벨 시작 칸을 확인하세요.');const count=Math.min(capacity,rows.length-from+1);$('data-preview').textContent=rows.slice(from-1,from-1+Math.min(3,count)).map((t,i)=>`${from+i}행 → ${start+i}번\n${t}`).join('\n\n');$('data-summary').textContent=`총 ${rows.length}행 · 이번에 ${count}칸 입력 · 남은 ${Math.max(0,rows.length-from+1-count)}행은 다음 용지에서 입력하세요. 해당 칸의 기존 문구를 바꿉니다.`;$('apply-data').disabled=false;}catch(e){$('data-summary').textContent=e.message;$('apply-data').disabled=true;}}
$('data-sheet').addEventListener('change',loadSheet);for(const id of ['data-template','data-row-start','data-label-start'])$(id).addEventListener('input',previewData);
$('apply-data').addEventListener('click',()=>{try{const rows=values(),from=Number($('data-row-start').value)-1,start=Number($('data-label-start').value)-1;previewData();if($('apply-data').disabled)return;undo={project:getProject(),product:getProject().product,texts:getProject().labels.map(l=>l.text)};const n=Math.min(rows.length-from,getProject().labels.length-start);change(s=>{for(let i=0;i<n;i++)s.labels[start+i].text=rows[from+i];});$('undo-data').disabled=false;message(`${n}칸에 문구를 입력했습니다. PDF에서 넘침을 확인하세요.`);}catch(e){message(e);}});
$('undo-data').addEventListener('click',()=>{if(!undo||getProject()!==undo.project||getProject().product!==undo.product||getProject().labels.length!==undo.texts.length){message('프로젝트가 바뀌어 되돌릴 수 없습니다.');return;}change(s=>s.labels.forEach((l,i)=>l.text=undo.texts[i]));undo=null;$('undo-data').disabled=true;});
$('open-data').addEventListener('click',()=>{$('data-dialog').showModal();if(data)previewData();});
$('open-address').addEventListener('click',()=>$('address-dialog').showModal());
$('search-address').addEventListener('click',async()=>{try{if(!addressLoader)addressLoader=new Promise((res,rej)=>{const script=document.createElement('script');script.src='https://t1.kakaocdn.net/mapjsapi/bundle/postcode/prod/postcode.v2.js';script.onload=res;script.onerror=()=>{addressLoader=null;script.remove();rej(Error('주소 검색 서비스를 불러오지 못했습니다. 직접 입력하거나 연결을 확인하세요.'));};document.head.append(script);});await addressLoader;const service=root.kakao?.Postcode||root.daum?.Postcode;if(!service)throw Error('주소 검색 서비스를 사용할 수 없습니다.');$('address-search-frame').hidden=false;new service({width:'100%',height:'100%',oncomplete:d=>{$('address-postcode').value=d.zonecode;$('address-main').value=d.userSelectedType==='R'?d.roadAddress:d.jibunAddress;$('address-search-frame').hidden=true;$('address-detail').focus();}}).embed($('address-search-frame'));}catch(e){message(e);}});
$('apply-address').addEventListener('click',()=>{const text=[$('address-postcode').value,$('address-main').value,$('address-detail').value,$('address-recipient').value].map(s=>s.trim()).filter(Boolean).join('\n');if(!$('address-main').value.trim()||text.length>1000){message('주소를 입력해 주세요.');return;}change((s,l)=>l.text=text);$('address-dialog').close();notify('선택한 라벨에 주소를 입력했습니다.');});
return{refresh(){if($('studio-dialog').open)refresh();}};
};})(globalThis);
