(function(root,factory){if(typeof module==='object'&&module.exports)module.exports=factory();else root.LabelStudio=factory();})(globalThis,()=>{
  'use strict';
  const MAX_ASSET=12*1024*1024,MAX_TOTAL=24*1024*1024;
  function box(b,g){return b&&['x','y','width','height'].every(k=>Number.isFinite(b[k]))&&b.x>=0&&b.y>=0&&b.width>0&&b.height>0&&b.x+b.width<=g.width+1e-6&&b.y+b.height<=g.height+1e-6;}
  function validText(t,g){return t&&typeof t.text==='string'&&t.text.length<=1000&&['sans','serif','mono'].includes(t.font)&&Number.isFinite(t.size)&&t.size>=6&&t.size<=48&&/^#[0-9a-f]{6}$/i.test(t.color)&&typeof t.bold==='boolean'&&['left','center','right'].includes(t.align)&&box(t.textBox,g)&&(!Object.hasOwn(t,'z')||Number.isFinite(t.z));}
  function textItems(l){return[{...l,z:l.textZ??100},...(l.textBoxes||[]).map((t,i)=>({...t,z:t.z??101+i}))];}
  function valid(s){if(!s||!Array.isArray(s.labels)||!s.geometry)return false;const assets=s.assets||{};if(typeof assets!=='object'||Array.isArray(assets))return false;let bytes=0;for(const [key,a] of Object.entries(assets)){if(!/^[a-zA-Z0-9_-]{1,80}$/.test(key)||!a||typeof a.data!=='string'||a.data.length>MAX_ASSET||!/^data:image\/(png|jpeg);base64,[A-Za-z0-9+/]+={0,2}$/.test(a.data))return false;bytes+=a.data.length;}if(bytes>MAX_TOTAL)return false;return s.labels.every(l=>l&&(!Object.hasOwn(l,'textZ')||Number.isFinite(l.textZ))&&(!l.textBoxes||(Array.isArray(l.textBoxes)&&l.textBoxes.length<=19&&l.textBoxes.every(t=>validText(t,s.geometry))))&&(!l.textBox||box(l.textBox,s.geometry))&&(!l.images||(Array.isArray(l.images)&&l.images.length<=20&&l.images.every(i=>box(i,s.geometry)&&(!Object.hasOwn(i,'z')||Number.isFinite(i.z))&&Object.hasOwn(assets,i.assetId)))));}
  function prune(s){const ids=new Set(s.labels.flatMap(l=>(l.images||[]).map(i=>i.assetId)));if(s.assets)for(const id of Object.keys(s.assets))if(!ids.has(id))delete s.assets[id];}
  function fit(b,g){const f=Math.min(1,g.width/b.width,g.height/b.height);const width=b.width*f,height=b.height*f;return{...b,width,height,x:Math.max(0,Math.min(b.x,g.width-width)),y:Math.max(0,Math.min(b.y,g.height-height))};}
  function table(matrix){if(!Array.isArray(matrix)||matrix.length<2)throw Error('첫 행에 열 제목, 다음 행부터 자료를 넣어 주세요.');if(matrix.length>10001)throw Error('자료는 최대 10,000행까지 지원합니다.');const seen=new Set();const headers=matrix[0].map((v,i)=>{let name=String(v??'').trim()||`열${i+1}`;name=name.replace(/[{}]/g,'');let n=name,c=2;while(seen.has(n))n=`${name}_${c++}`;seen.add(n);return n;});if(headers.length>100)throw Error('열은 최대 100개까지 지원합니다.');return{headers,rows:matrix.slice(1).filter(row=>row.some(v=>String(v??'').trim())).map(row=>headers.map((_,i)=>String(row[i]??'')))};}
  function merge(data,pattern){const used=[...pattern.matchAll(/\{\{([^{}]+)\}\}/g)].map(m=>m[1]);if(!used.length)throw Error('열 버튼을 눌러 {{열 이름}}을 문구에 넣어 주세요.');for(const h of used)if(!data.headers.includes(h))throw Error(`없는 열 이름: ${h}`);return data.rows.map(row=>{const text=pattern.replace(/\{\{([^{}]+)\}\}/g,(_,h)=>row[data.headers.indexOf(h)]);if(text.length>1000)throw Error('일부 행의 문구가 1,000자를 넘습니다.');return text;});}
  function columnName(index){let name='';for(let n=index+1;n;n=Math.floor((n-1)/26))name=String.fromCharCode(65+(n-1)%26)+name;return name;}
  function cellMerge(matrix,pattern,advance=false){
    const refs=[...pattern.matchAll(/\{\{([^{}]+)\}\}/g)];if(!refs.length)throw Error('주소록 셀을 누르거나 {{A1}} 형식으로 입력하세요.');
    const parsed=refs.map(m=>{const match=/^([A-Z]+)([1-9]\d*)$/i.exec(m[1].trim());if(!match)throw Error(`셀 주소가 올바르지 않습니다: ${m[1]}`);const col=[...match[1].toUpperCase()].reduce((n,c)=>n*26+c.charCodeAt(0)-64,0)-1,row=Number(match[2])-1;const width=Math.max(0,...matrix.map(r=>r.length));if(col>=width||row>=matrix.length)throw Error(`자료 범위를 벗어난 셀: ${m[1]}`);return{key:m[0],col,row};});
    const count=advance?matrix.length-Math.max(...parsed.map(p=>p.row)):1;
    return Array.from({length:count},(_,offset)=>{const text=pattern.replace(/\{\{([^{}]+)\}\}/g,token=>{const p=parsed.find(p=>p.key===token);return String(matrix[p.row+offset]?.[p.col]??'');});if(text.length>1000)throw Error('일부 문구가 1,000자를 넘습니다.');return text;});
  }
  return{MAX_ASSET,MAX_TOTAL,box,valid,prune,fit,table,merge,columnName,cellMerge,textItems};
});
