const fs=require('node:fs'),path=require('node:path'),http=require('node:http'),assert=require('node:assert/strict');
const{chromium}=require('playwright'),XLSX=require('../vendor/xlsx.full.min.js');const root=path.resolve(__dirname,'..');
const server=http.createServer((req,res)=>{const name=decodeURIComponent(req.url.split('?')[0]),file=path.resolve(root,'.'+(name==='/'?'/index.html':name));if(!file.startsWith(root+path.sep)){res.writeHead(403).end();return;}try{const data=fs.readFileSync(file),ext=path.extname(file);res.setHeader('Content-Type',({'.html':'text/html; charset=utf-8','.js':'application/javascript; charset=utf-8','.css':'text/css; charset=utf-8','.ttf':'font/ttf'})[ext]||'application/octet-stream');res.end(data);}catch{res.writeHead(404).end();}});
(async()=>{await new Promise(r=>server.listen(0,'127.0.0.1',r));let browser;try{browser=await chromium.launch({headless:true});const page=await browser.newPage({viewport:{width:1440,height:1050}}),errors=[],external=[];page.on('pageerror',e=>errors.push(e.message));page.on('request',r=>{if(!r.url().startsWith('http://127.0.0.1')&&!r.url().startsWith('data:')&&!r.url().startsWith('blob:'))external.push(r.url());});await page.goto('http://127.0.0.1:'+server.address().port);await page.locator('#sheet .label').first().waitFor();await page.evaluate(()=>document.fonts.ready);
// Dense miniatures must fit every grid item inside their frame.
await page.locator('[data-brand=formtec]').click();await page.locator('#search').fill('3100');assert.ok(await page.locator('.mini-sheet').first().evaluate(el=>{const b=el.getBoundingClientRect();return [...el.children].every(c=>{const r=c.getBoundingClientRect();return r.bottom<=b.bottom+.1&&r.right<=b.right+.1;});}));await page.locator('[data-brand=any]').click();
await page.locator('#open-studio').click();const png=await page.evaluate(()=>{const c=document.createElement('canvas');c.width=160;c.height=80;const x=c.getContext('2d');x.fillStyle='#4b8154';x.fillRect(0,0,160,80);x.fillStyle='white';x.fillRect(20,20,120,40);return c.toDataURL('image/png').split(',')[1];});await page.locator('#image-file').setInputFiles({name:'test.png',mimeType:'image/png',buffer:Buffer.from(png,'base64')});await page.locator('.studio-image').waitFor();assert.equal(await page.locator('#sheet .label-image').count(),1);
const before=await page.locator('#image-x').inputValue(),bounds=await page.locator('.studio-image').boundingBox();await page.mouse.move(bounds.x+10,bounds.y+10);await page.mouse.down();await page.mouse.move(bounds.x+30,bounds.y+20);await page.mouse.up();assert.notEqual(await page.locator('#image-x').inputValue(),before);
await page.evaluate(async p=>{const bytes=Uint8Array.from(atob(p),c=>c.charCodeAt(0)),dt=new DataTransfer();dt.items.add(new File([bytes],'paste.png',{type:'image/png'}));document.querySelector('#studio-dialog').dispatchEvent(new ClipboardEvent('paste',{clipboardData:dt,bubbles:true}));},png);await page.waitForFunction(()=>document.querySelectorAll('.studio-image').length===2);
await page.screenshot({path:path.join(root,'tmp/studio-editor.png')});await page.locator('#studio-dialog .close-dialog').click();
const wb=XLSX.utils.book_new();XLSX.utils.book_append_sheet(wb,XLSX.utils.aoa_to_sheet([['이름','우편번호'],['홍길동','00123'],['김라벨','04567']]),'주소록');await page.locator('#open-data').click();await page.locator('#data-file').setInputFiles({name:'addresses.xlsx',mimeType:'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',buffer:Buffer.from(XLSX.write(wb,{type:'buffer',bookType:'xlsx'}))});await page.waitForFunction(()=>!document.querySelector('#apply-data').disabled);assert.match(await page.locator('#data-preview').textContent(),/00123/);await page.locator('#apply-data').click();await page.locator('#data-dialog .close-dialog').click();assert.equal(await page.locator('#content').inputValue(),'홍길동\n00123');await page.reload();assert.equal(await page.locator('#sheet .label-image').count(),2);
// Address book cells preserve physical Excel row numbers and can target a separate text box.
await page.locator('#open-studio').click();await page.locator('#add-text').click();await page.locator('#object-text').fill('보조 문구');await page.locator('#object-size').fill('8');await page.locator('#object-size').dispatchEvent('change');for(const [axis,value] of [['x','3'],['y','3'],['width','50'],['height','12']]){await page.locator('#image-'+axis).fill(value);await page.locator('#image-'+axis).dispatchEvent('change');}
await page.locator('#image-forward').click();let obj=await page.locator('[data-object="text:1"]').boundingBox();await page.mouse.move(obj.x+10,obj.y+10);await page.mouse.down();await page.mouse.move(obj.x+20,obj.y+15);await page.mouse.up();const sizeBefore=await page.locator('#image-width').inputValue();const handle=await page.locator('.object-resize').boundingBox();await page.mouse.move(handle.x+5,handle.y+5);await page.mouse.down();await page.mouse.move(handle.x+15,handle.y+10);await page.mouse.up();assert.notEqual(await page.locator('#image-width').inputValue(),sizeBefore);
await page.locator('#object-data').click();assert.equal(await page.locator('#data-target').inputValue(),'1');
// Reload workbook after the page reload above, retaining the target object.
await page.locator('#data-file').setInputFiles({name:'addresses.xlsx',mimeType:'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',buffer:Buffer.from(XLSX.write(wb,{type:'buffer',bookType:'xlsx'}))});await page.waitForFunction(()=>!document.querySelector('#show-addressbook').disabled);await page.locator('#data-template').fill('');await page.locator('#show-addressbook').click();assert.equal(await page.locator('[data-cell="A1"]').textContent(),'이름');await page.locator('[data-cell="A2"]').click();await page.locator('#addressbook-search').fill('김라벨');assert.equal(await page.locator('[data-cell="A3"]').textContent(),'김라벨');assert.equal(await page.locator('[data-cell="A2"]').count(),0);await page.locator('.close-addressbook').click();assert.equal(await page.locator('#data-template').inputValue(),'{{A2}}');assert.equal(await page.locator('#data-ref-mode').inputValue(),'cells');await page.locator('#cell-advance').check();await page.locator('#apply-data').click();await page.locator('#data-dialog .close-dialog').click();assert.equal(await page.locator('#object-text').inputValue(),'홍길동');await page.screenshot({path:path.join(root,'tmp/multi-object.png')});await page.locator('#studio-dialog .close-dialog').click();assert.equal(await page.locator('#sheet .label-textbox').nth(1).textContent(),'김라벨');
const finalState=await page.evaluate(()=>JSON.parse(localStorage.getItem('ohmylabel.project.v1')));assert.equal(finalState.labels[0].textBoxes[0].text,'홍길동');assert.equal(finalState.labels[0].text,'홍길동\n00123');assert.ok(finalState.labels[0].textBoxes[0].textBox.width>50);await page.reload();assert.equal(await page.locator('#sheet .label-textbox').count(),2);
const bytes=await page.evaluate(async()=>Array.from((await LabelPDF.create(JSON.parse(localStorage.getItem('ohmylabel.project.v1')))).bytes));fs.writeFileSync(path.join(root,'tmp/studio.pdf'),Buffer.from(bytes));
await page.locator('#open-address').click();await page.locator('#address-main').fill('서울특별시 테스트로 1');await page.locator('#address-detail').fill('101호');await page.locator('#address-recipient').fill('테스트');await page.locator('#apply-address').click();assert.match(await page.locator('#content').inputValue(),/101호/);assert.deepEqual(external,[],'local images and workbook must not produce external requests');
// Stub only the provider response; verify selected address is wired correctly.
await page.route('https://t1.kakaocdn.net/**',r=>r.fulfill({contentType:'application/javascript',body:'window.kakao={Postcode:function(o){this.embed=function(){o.oncomplete({zonecode:"01234",userSelectedType:"R",roadAddress:"서울특별시 예제로 2"})}}}'}));await page.locator('#open-address').click();await page.locator('#search-address').click();await page.waitForFunction(()=>document.querySelector('#address-postcode').value==='01234');assert.equal(await page.locator('#address-main').inputValue(),'서울특별시 예제로 2');await page.locator('#address-dialog .close-dialog').click();await page.setViewportSize({width:390,height:844});await page.locator('#open-studio').click();await page.screenshot({path:path.join(root,'tmp/studio-mobile.png')});assert.deepEqual(errors,[]);console.log('PASS: real Chromium upload, image paste/drag, dense thumbnails, XLSX mapping, persistence, image PDF, offline data processing, and address response wiring.');
}finally{if(browser)await browser.close();await new Promise(r=>server.close(r));}})().catch(e=>{console.error(e);process.exitCode=1;});
